### ISSUE TITLE
tkgui not working (topoconsole doesn't appear)

### ISSUE THREAD

**Issue by ceball** [ioam/topographica#611]
I was at CNV-2014-638-ga3ab76f and `./topographica -g` worked fine. I updated to the most recent version (CNV-2014-700-g6112f71) and now `./topographica -g` gives me a topoconsole window that's not expanded. If I type `topo.guimain.mainloop()` the topoconsole expands but then I can't use the console any more.

---

(likely to be irrelevant from here on...) I'm using anaconda python 2.1.0 on DICE, but probably that's irrelevant, because Jan also reports the same problem on Ubuntu (not sure which version) using the system python. I tried to use DICE's python but I got a syntax error earlier on in the startup unrelated to this issue (DICE's python is too old, I guess? I tried `dice-pyenv CNV` too, but it said `Environment CNV could not be found`). I also tried to use Ubuntu 12's python, but I guess my matplotlib version is too old (ImportError: cannot import name rc_params_from_file) and when I did `pip install --user --upgrade matplotlib` I got:

>    The required version of distribute (>=0.6.28) is not available,
>    and can't be installed while this script is running. Please
>    install a more recent version first, using
>    'easy_install -U distribute'.

I tried that command, but got 

> [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages'

I didn't want to use sudo, so I tried the easy_install command again with `--user` and it worked (because I have ~/.local/bin on my path, I guess), so I tried to pip install matplotlib again but that failed with several pages of instructions...so I stopped there (I guess I need to install some libraries).

**Comment by mjabri** [comment]
I am not sure where this issue's conclusion was at, but i just want to note that with latest topographica on github as on yesterday 17 Oct 2015:
1. A "backend: agg" in matplotlibrc is necessary for the GUI to expand.
2. If you do 1., then matplotlib plots no longer show up when plotted from the topographica prompt.

**Comment by philippjfr** [comment]
Just pushed a fix for this along with a fix for the projections in the GUI. Could you pull the latest version of Topographica along with the submodules and report back?

**Comment by mjabri** [comment]
Thanks Philipp. I just pulled a fresh clone. Plotting is ok now, but i still get key error when i try to plot projections (e.g. ./topographica -g ./examples/gcal.ty). Here the trace when i tried to plot LGN and V1 projections.


[143][marwan@synapse:topographica]> ./topographica -g ./examples/gcal.ty 
Launching GUI
Output path: /home/marwan/Documents/Topographica

Welcome to Topographica!

Type help() for interactive help with python, help(topo) for general
information about Topographica, help(commandname) for info on a
specific command, or topo.about() for info on this release, including
licensing information.

<IPython.core.display.HTML object>

topo_t000000.00_c1>>> WARNING:root:Time: 000001.00 TopoConsole01074: (KeyError) 'Afferent'
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 671, in <lambda>
    tkvar.trace_variable('w',lambda a,b,c,p_name=name: self._handle_gui_set(p_name))
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 1339, in _handle_gui_set
    self._update_param_from_tkvar(p_name,force)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 1332, in _update_param_from_tkvar
    super(TkParameterized,self)._update_param_from_tkvar(param_name)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 798, in _update_param_from_tkvar
    tkvar._on_modify()
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/plotgrouppanel.py", line 40, in busy_fn
    fn(widget,*args,**kw)
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/plotgrouppanel.py", line 428, in redraw_plots
    self.plotgroup.make_plots(update=False)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 113, in make_plots
    self._create_images(update)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 163, in _create_images
    self.plots = [plot for plot in self._generate_plots() if plot is not None]
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 582, in _generate_plots
    return self._static_plots[:]+self._template_plots(range_=range_)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 795, in _template_plots
    return super(ProjectionSheetPlotGroup,self)._template_plots(range_=named_ranges)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 633, in _template_plots
    template_plots.append(self._make_template_plot(plot_template_name,plot_template,**kw))
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 1169, in _make_template_plot
    view_dict = {'Strength': kw['proj'].dest.views.CFs[kw['proj'].name],
  File "/opt-local/git-topographica/latest/topographica/external/holoviews/holoviews/core/layout.py", line 493, in __getitem__
    return super(Layout, self).__getitem__(key)
  File "/opt-local/git-topographica/latest/topographica/external/holoviews/holoviews/core/tree.py", line 171, in __getitem__
    raise KeyError(identifier)
KeyError: 'Afferent'
WARNING:root:Time: 000001.00 TopoConsole01074: (KeyError) 'LGNOnAfferent'
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 671, in <lambda>
    tkvar.trace_variable('w',lambda a,b,c,p_name=name: self._handle_gui_set(p_name))
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 1339, in _handle_gui_set
    self._update_param_from_tkvar(p_name,force)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 1332, in _update_param_from_tkvar
    super(TkParameterized,self)._update_param_from_tkvar(param_name)
  File "/opt-local/git-topographica/latest/topographica/external/paramtk/paramtk/__init__.py", line 798, in _update_param_from_tkvar
    tkvar._on_modify()
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/projectionpanel.py", line 289, in sheet_change
    super(ProjectionPanel,self).sheet_change()
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/projectionpanel.py", line 195, in sheet_change
    self.redraw_plots()
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/plotgrouppanel.py", line 40, in busy_fn
    fn(widget,*args,**kw)
  File "/opt-local/git-topographica/latest/topographica/topo/tkgui/plotgrouppanel.py", line 428, in redraw_plots
    self.plotgroup.make_plots(update=False)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 113, in make_plots
    self._create_images(update)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 163, in _create_images
    self.plots = [plot for plot in self._generate_plots() if plot is not None]
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 582, in _generate_plots
    return self._static_plots[:]+self._template_plots(range_=range_)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 795, in _template_plots
    return super(ProjectionSheetPlotGroup,self)._template_plots(range_=named_ranges)
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 633, in _template_plots
    template_plots.append(self._make_template_plot(plot_template_name,plot_template,**kw))
  File "/opt-local/git-topographica/latest/topographica/topo/plotting/plotgroup.py", line 1169, in _make_template_plot
    view_dict = {'Strength': kw['proj'].dest.views.CFs[kw['proj'].name],
  File "/opt-local/git-topographica/latest/topographica/external/holoviews/holoviews/core/layout.py", line 493, in __getitem__
    return super(Layout, self).__getitem__(key)
  File "/opt-local/git-topographica/latest/topographica/external/holoviews/holoviews/core/tree.py", line 171, in __getitem__
    raise KeyError(identifier)
KeyError: 'LGNOnAfferent'

**Comment by philippjfr** [comment]
Seems like I can reproduce it now at least. Seems to work fine for tiny.ty but not for gcal.ty. Hopefully I'll have a fix soon.

**Comment by mjabri** [comment]
Great, that helps :)
