### ISSUE TITLE
problem of running gcal.py in the "models"file error : AttributeError: 'module' object has no attribute 'SeparatedComposite'

### ISSUE THREAD

**Issue by wenqi2015** [ioam/topographica#622]
I installed topographica following the instruction here : https://github.com/ioam/topographica

Then I run the script of gcal.py in the "stevens.jn13" file of the "models"file , then it shows the error:

Traceback (most recent call last):
  File "./topographica", line 17, in <module>
    process_argv(sys.argv[1:])
  File "/home/wenqi/env/topographica/topo/misc/commandline.py", line 739, in process_argv
    execfile(filename,__main__.__dict__)
  File "models/stevens.jn13/1.ty", line 142, in <module>
    combined_inputs = pattern.SeparatedComposite(min_separation=0,generators=inputs,
AttributeError: 'module' object has no attribute 'SeparatedComposite'

I really need to solve this problem, could you help me this please ?

**Comment by wenqi2015** [comment]
Sorry, I forgot to mention, I installed topographica in 28th, April, 2015

**Comment by jbednar** [comment]
SeparatedComposite has recently moved locations, so please replace "pattern.SeparatedComposite" with "imagen.deprecated.SeparatedComposite" in the .ty file.  We'll need to update files in models/, but have not done so yet.  Thanks! 

-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by wenqi2015** [comment]
Thanks a lot ! Now it can work !
