### ISSUE TITLE
can't convert to FixedPoint: None

### ISSUE THREAD

**Issue by kalok87** [ioam/topographica#639]
Traceback (most recent call last):
  File "/home/kalok/topographica/topographica", line 17, in <module>
    process_argv(sys.argv[1:])
  File "/home/kalok/topographica/topo/misc/commandline.py", line 758, in process_argv
    execfile(filename,__main__.__dict__)
  File "/home/kalok/Documents/map_sim/task_142/stevens.jn13/gcal.ty", line 323, in <module>
    data = measure_or_pref()
  File "/home/kalok/topographica/external/param/param/parameterized.py", line 1847, in __new__
    return inst.__call__(*args,**params)
  File "/home/kalok/topographica/external/featuremapper/featuremapper/command.py", line 123, in __call__
    pattern_response_fn=p.pattern_response_fn)
  File "/home/kalok/topographica/external/param/param/parameterized.py", line 1847, in __new__
    return inst.__call__(*args,**params)
  File "/home/kalok/topographica/external/featuremapper/featuremapper/__init__.py", line 485, in __call__
    results = self._collate_results(p)
  File "/home/kalok/topographica/external/featuremapper/featuremapper/__init__.py", line 554, in _collate_results
    label=name, group=map_label)
  File "/home/kalok/topographica/external/holoviews/holoviews/core/ndmapping.py", line 707, in __init__
    super(UniformNdMapping, self).__init__(initial_items, **params)
  File "/home/kalok/topographica/external/holoviews/holoviews/core/ndmapping.py", line 115, in __init__
    self._add_item(initial_items[0], initial_items[1])
  File "/home/kalok/topographica/external/holoviews/holoviews/core/ndmapping.py", line 158, in _add_item
    dim_vals = tuple(v if None in [t, v] else t(v) for t, v in dim_types)
  File "/home/kalok/topographica/external/holoviews/holoviews/core/ndmapping.py", line 158, in <genexpr>
    dim_vals = tuple(v if None in [t, v] else t(v) for t, v in dim_types)
  File "/home/kalok/topographica/topo/misc/fixedpoint.py", line 338, in __cmp__
    xn, yn, p = _norm(self, other, FixedPoint=type(self))
  File "/home/kalok/topographica/topo/misc/fixedpoint.py", line 504, in _norm
    y = FixedPoint(y, x.p)
  File "/home/kalok/topographica/topo/misc/fixedpoint.py", line 258, in __init__
    raise TypeError("can't convert to FixedPoint: " + `value`)
TypeError: can't convert to FixedPoint: None

Hallo, I just try to run my simulation and then I got this error. What is this problem and how can I fix it? I really need some helps, thank you!

**Comment by philippjfr** [comment]
Do you have gmpy installed?
