### ISSUE TITLE
Quitting gives errors if progress bar open

### ISSUE THREAD

**Issue by sf-issues** [ioam/topographica#97]
Converted from SourceForge issue 2191521, submitted by jbednar
Submit Date: 2008-10-24 09:43 GMT

Quitting from the GUI while Topographica is working on something (with a progress bar window up) gives an error like the one below.  This isn't a serious problem, but would be good to fix.

Jim

topo_t000000.00_c1>>> Quit selected; exiting
Exception in Tkinter callback
Traceback (most recent call last):
  File "/disk/scratch/jbednar/topographica//lib/python2.5/lib-tk/Tkinter.py", line 1403, in __call__
    return self.func(*args)
  File "/disk/scratch/jbednar/topographica/topo/tkgui/projectionpanel.py", line 207, in refresh
    super(PlotMatrixPanel,self).refresh(update)
  File "/disk/scratch/jbednar/topographica/topo/tkgui/plotgrouppanel.py", line 487, in refresh
    self.refresh_plots()
  File "/disk/scratch/jbednar/topographica/topo/tkgui/plotgrouppanel.py", line 65, in busy_fn
    if 'cursor' in widget.configure():
  File "/disk/scratch/jbednar/topographica//lib/python2.5/lib-tk/Tkinter.py", line 1197, in configure
    return self._configure('configure', cnf, kw)
  File "/disk/scratch/jbednar/topographica//lib/python2.5/lib-tk/Tkinter.py", line 1181, in _configure
    self.tk.call(_flatten((self._w, cmd)))):
TclError: invalid command name ".178102956.178105132.178158508.178166540.178165100.178163756.178165420.178164076.178165548"

**Comment by ceball** [comment]
> Quitting gives errors if progress bar open
> ghost assigned ceball

Won't fix: Why would you ever want to quit topographica, I say :)
